### PR TITLE
Fix preview command sometimes not executing on Windows

### LINKED ISSUE #18: executeCommand() doesn't execute the checkpoint_paste() command
Terminals: GitBash and Conda through Powershell and GitBash
Issue replicated on 2 different PCs both Windows 11 one Enterprise and one Education (Version 23H2)
IPython version: 8.21.0

I've downloaded the repository, npm installed, npm compiled everything and attached the debugger.

Simple Manim Scene:

```py
from manimlib import *

class SubTensors(InteractiveScene):
    def construct(self):
        ## Interactions
        circle = Circle(radius = 2)
        self.play(DrawBorderThenFill(circle))
```

Detects the preview cell.
Run the command:

```sh
manimgl sub_tensor.py SubTensors -se 5
```

And when I click on the Preview Manim Cell, it clears the console, writes checkpoint_paste() but doesn't run it at all.

With the debugger, I can see that with both the `executeCommand` and `terminal.sendText`, the command is not executed.
If then I manually click ENTER in terminal, the command is executed, however it's now too late, the clipboard is already reset to the previous state and throws an error because it tries to run something that is not python code.

Since this happens with different terminals, I believe it's something due to the IPython console. Because if we just click `Preview Manim Cell`, without running the `manimgl` command, the command `checkpoint_paste()` is executed properly (even though, in this case, it's an error, since it's not recognized as a Powershell/Bash/Conda command).

What I have already tried:
 - Adding `\r\n` or `\n` at the end of the `PREVIEW_COMMAND` string
 - Adding spaces or other chars at the end of the `PREVIEW_COMMAND` string
 - `terminal.sendText` actually has a second parameter that is used to execute the command, setting that to `true`
 - Executing always `sendText` regardless if the terminal supports `shellIntegration`

Nothing worked. Any ideas as to why would this happen? I'm not familiar with the IPython console; it may have some weird interaction behaviour.

### PR DESCRIPTION
**Pull request by RickLuiken**
This PR attempts to fix the preview command on Windows. As seen in [this video](https://github.com/Manim-Notebook/manim-notebook/issues/18#issuecomment-2453048187), sometimes checkpoint_paste() is not executed in the IPython shell, but it triggers the multiline input in IPython. In this PR, I detect the multiline input ("...:") and send "\x7F" to clear the extra line and send another newline to actually execute the command. This seems to fix the issue on my side. Let me know if you have any issues on other platforms!

Fixes #18

### CODE REVIEW

**Comment by Splines** [comment]
Nice, thanks! I will check if this still works for me. Generally, I'd favor a solution where we don't have to additionally detect the `...:` string as that is of course one more thing where it could break in the future. So I assume the commands proposed in [my comment here](https://github.com/Manim-Notebook/manim-notebook/issues/18#issuecomment-2453461077) didn't work for you?

File: src/manimShell.ts [hunk 1]
```diff
@@ -657,6 +662,14 @@ export class ManimShell {
                         this.eventEmitter.emit(ManimShellEvent.IPYTHON_CELL_FINISHED);
                     }
 
+                    if (this.isExecutingCommand && data.match(IPYTHON_MULTILINE_START_REGEX)) {
+                        Logger.debug(`💨 IPython multiline detected, sending extra newline`);
+                        // use sendText instead of ManimShell.exec as
+                        // shell integration does not work here
+                        // \x7F deletes the extra line ("...:") from IPython
+                        this.activeShell.sendText("\x7F");
```
Comment (Splines) [inline src/manimShell.ts:670]: The [`ManimShell.exec()`](https://github.com/RickLuiken/manim-notebook/blob/4d31051d8ca9e7fbeb77afed3a4a9372ad27e409/src/manimShell.ts#L492-L506) method is also setting the `this.detectShellExecutionEnd` flag. Maybe add a default param to `exec()` like `forceSendTextFallback=False` (or similar, maybe you can come up with a better name) and only set it when calling it here upon a "continued IPython expression detection" (`...:`).

---

> shell integration does not work here

Also I assume you have tried it out with normal shell integration? What didn't work exactly in this case? Like even sending `\x7F` didn't get rid of the extra line?

**Review by Splines — CHANGES_REQUESTED** [review]

File: src/manimShell.ts (hunk 1 above)
Comment (RickLuiken) [reply src/manimShell.ts]: I did some more testing, and seems it works now with shell integration! Before when I used it, the command was not being executed, the only thing that happened was that the screen was cleared and a bunch of newlines were sent. I later added `this.isExecutingCommand` to the if statement to stop the extra newlines, and I assume that this has also fixed the issue I had with the shell integration.

**Comment by RickLuiken** [comment]
I would also want to find a better solution than this. However, others have run into the same issue on the [IPython repo](https://github.com/ipython/ipython/issues/13054) and the [vscode-python repo](https://github.com/microsoft/vscode-python/issues/17172), so it does not seem to have an easy fix.

This solution should work out of the box for new users. Adding a delay between writing the command and the newline requires users to tweak the delay value.

File: src/manimShell.ts [hunk 2]
```diff
@@ -17,6 +17,11 @@ const ANSI_CONTROL_SEQUENCE_REGEX = /(?:\x1B[@-Z\\-_]|[\x80-\x9A\x9C-\x9F]|(?:\x
  */
 const IPYTHON_CELL_START_REGEX = /^\s*In \[\d+\]:/gm;
 
+/**
+ * Regular expression to match IPython multiline input "...:"
+ */
+const IPYTHON_MULTILINE_START_REGEX = /^\s*\.{3}:\s+$/m;
+
```
Comment (Splines) [inline src/manimShell.ts:24]: Could you add a few more words here explaining the context of why this is added? E.g. summarize the issue you had in a few sentences, explain what multiline input in IPython means and that this detection here is rather a hack as no easy solution was otherwise found. Just as a note for our future selves.

File: src/manimShell.ts [hunk 3]
```diff
@@ -657,6 +662,12 @@ export class ManimShell {
                         this.eventEmitter.emit(ManimShellEvent.IPYTHON_CELL_FINISHED);
                     }
 
+                    if (this.isExecutingCommand && data.match(IPYTHON_MULTILINE_START_REGEX)) {
+                        Logger.debug(`💨 IPython multiline detected, sending extra newline`);
```
Comment (Splines) [inline src/manimShell.ts:666]: haha nice emoji

File: src/manimShell.ts [hunk 4]
```diff
@@ -657,6 +662,12 @@ export class ManimShell {
...
+                        // \x7F deletes the extra line ("...:") from IPython
```
Comment (Splines) [inline src/manimShell.ts:667]: Ok, that's funny, so it suffices to send a `DEL` (`\x7F`) to make IPython continue? But in contrary, appending a `\r\n` or `\n` or `\r` to the `checkpoint_paste()` command won't work? What a strange bug...

File: src/previewCode.ts [hunk 5]
```diff
@@ -4,9 +4,8 @@ import { ManimShell } from './manimShell';
 import { EventEmitter } from 'events';
 import { Logger } from './logger';
 
-const PREVIEW_COMMAND = `\x0C checkpoint_paste()\x1b`;
+const PREVIEW_COMMAND = `\x0Ccheckpoint_paste()`;
 // \x0C: is Ctrl + L
```
Comment (Splines) [inline src/previewCode.ts:8]: feel free to now also move the comment on top of or to the side of the line that defines `PREVIEW_COMMAND`

**Review by Splines — CHANGES_REQUESTED** [review]
Thanks, looks good to me, just a few more minor comments.

**Comment by Splines** [comment]
> This solution should work out of the box for new users. Adding a delay between writing the command and the newline requires users to tweak the delay value.

Yeah, this solution is definitely better than adding a delay. I just hope there will be a solution that gets to the root of this problem by means of a fix in the IPython repo or somewhere else where something like this would be tackled. But for now, if this fixes your problem that's already great and luckily this is also a fix that might be easily revertible once a solution is found in the future.

File: src/previewCode.ts [hunk 6]
```diff
@@ -4,9 +4,8 @@ import { ManimShell } from './manimShell';
 import { EventEmitter } from 'events';
 import { Logger } from './logger';
 
-const PREVIEW_COMMAND = `\x0C checkpoint_paste()\x1b`;
```
Comment (VladimirFokow) [inline src/previewCode.ts:7]: just for clarification:
removing `\x1b` - won't break the https://github.com/bhoov/manim-notebook/issues/18#issuecomment-2431146809 ?

File: src/manimShell.ts (hunk 4 above)
Comment (RickLuiken) [reply src/manimShell.ts:674]: Yes, it has to do something with the timing of sending the newline... If you paste something in IPython, it also does not execute it immediately (which is probably intended)

File: src/previewCode.ts (hunk 6 above)
Comment (VladimirFokow) [reply src/previewCode.ts:7]: thanks

**Comment by RickLuiken** [comment]
Sadly, I tried again with shell integration and this time it broke again... After some debugging I found that it thinks that there is a command running after sending the checkpoint_paste(). So, when sending the extra newline, it will first send a CTRL+C to stop the first command, deleting the checkpoint_paste() line. I haven't been able to break the sendText method, so let's stick to that for now.

File: src/previewCode.ts (hunk 6 above)
Comment (Splines) [reply src/previewCode.ts:7]: [related](https://github.com/Manim-Notebook/manim-notebook/issues/18#issuecomment-2453461077)

**Comment by Splines** [comment]
Great, thanks for addressing all the points. The code looks good to me now. I just want to test this out a bit on my machine and ensure it doesn't break anything for me (we definitely need unit and integration tests in the very near future🙈, see #47). I will probably only be able to report on Friday as I'm a bit busy beforehand.

**Review by Splines — APPROVED** [review]
Thanks! I've tested it on my machine and it works fine. I've also checked that users can still enter the multi-line mode, e.g. when they manually type in a for-loop in the IPython shell. It works since you check for `this.isExecutingCommand` 👍
